using CPQ.Core.Consumers;
using CPQ.Core.Exceptions;
using CPQ.Core.Extensions;
using CPQ.Core.Persistence.SessionFactories;
using CPQ.Core.Services;
using DomuWave.Services.Command.BillingGroup;
using DomuWave.Services.Dto.BillingGroup;
using DomuWave.Services.Interfaces.Extensions;
using DomuWave.Services.Models;
using NHibernate.Linq;
using SimpleMediator.Core;

namespace DomuWave.Services.Consumers;

public class ApplySuggestedBillingGroupsCommandConsumer
    : InMemoryConsumerBase<ApplySuggestedBillingGroupsCommand, IList<BillingGroupReadDto>>
{
    private readonly IUserService _userService;

    public ApplySuggestedBillingGroupsCommandConsumer(
        ISessionFactoryProvider sessionFactoryProvider,
        IUserService            userService) : base(sessionFactoryProvider)
    {
        _userService = userService;
    }

    protected override async Task<IList<BillingGroupReadDto>> Consume(
        ApplySuggestedBillingGroupsCommand command,
        IMediationContext                   mediationContext,
        CancellationToken                  cancellationToken)
    {
        var currentUser = await _userService.GetByIdAsync(command.CurrentUserId, cancellationToken)
            .ConfigureAwait(false);

        var condominium = await session.Query<Models.Condominium>()
            .Where(c => c.Id == command.CondominiumId && !c.IsDeleted)
            .FirstOrDefaultAsync(cancellationToken)
            .ConfigureAwait(false);

        if (condominium == null)
            throw new NotFoundException("Condominio non trovato.");

        var created = new List<DomuWave.Services.Models.BillingGroup>();

        foreach (var suggestion in command.Suggestions)
        {
            if (string.IsNullOrWhiteSpace(suggestion.SuggestedName) || suggestion.Units.Count < 2)
                continue;

            var entity = new DomuWave.Services.Models.BillingGroup
            {
                Condominium     = condominium,
                Tenant          = condominium.Tenant,
                Name            = suggestion.SuggestedName,
                ContactEmail    = suggestion.ContactEmail,
                IsAutoGenerated = true,
            };
            entity.Trace(currentUser);
            await session.SaveAsync(entity, cancellationToken).ConfigureAwait(false);

            var unitIds = suggestion.Units.Select(u => u.UnitId).ToList();
            var units = await session.Query<RealEstateUnit>()
                .Where(u => unitIds.Contains(u.Id) && !u.IsDeleted)
                .ToListAsync(cancellationToken)
                .ConfigureAwait(false);

            foreach (var unit in units)
            {
                unit.BillingGroup = entity;
                unit.Trace(currentUser);
                await session.UpdateAsync(unit, cancellationToken).ConfigureAwait(false);
            }

            created.Add(entity);
        }

        await session.FlushAsync(cancellationToken).ConfigureAwait(false);

        foreach (var g in created)
            await NHibernate.NHibernateUtil.InitializeAsync(g.Units, cancellationToken)
                .ConfigureAwait(false);

        return created.Select(g => g.ToReadDto()).ToList();
    }
}
