using CPQ.Core.DTO;

namespace DomuWave.Services.Dto.BillingGroup;

public class BillingGroupReadDto : TraceEntityDTO<int>
{
    public int    CondominiumId   { get; set; }
    public string CondominiumName { get; set; }
    public string Name            { get; set; }
    public string ContactEmail    { get; set; }
    public string ContactPhone    { get; set; }
    public string Notes           { get; set; }
    public bool   IsAutoGenerated { get; set; }

    public IList<BillingGroupUnitDto> Units { get; set; } = new List<BillingGroupUnitDto>();
}

public class BillingGroupUnitDto
{
    public int    UnitId             { get; set; }
    public string InternalNumber     { get; set; }
    public string DisplayName        { get; set; }
    public string UnitType           { get; set; }
}
