<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Models\Mappings\Budget.hbm.xml" />
    <None Remove="Models\Mappings\BudgetItem.hbm.xml" />
    <None Remove="Models\Mappings\BudgetStatus.hbm.xml" />
    <None Remove="Models\Mappings\ChartOfAccounts.hbm.xml" />
    <None Remove="Models\Mappings\ChartOfAccountsCategory.hbm.xml" />
    <None Remove="Models\Mappings\ChartOfAccountsCategoryTemplate.hbm.xml" />
    <None Remove="Models\Mappings\ChartOfAccountsTemplate.hbm.xml" />
    <None Remove="Models\Mappings\ChartOfAccountsTemplateItem.hbm.xml" />
    <None Remove="Models\Mappings\Communication.hbm.xml" />
    <None Remove="Models\Mappings\CommunicationRead.hbm.xml" />
    <None Remove="Models\Mappings\Condominium.hbm.xml" />
    <None Remove="Models\Mappings\CondominiumAddress.hbm.xml" />
    <None Remove="Models\Mappings\CondominiumCadastralData.hbm.xml" />
    <None Remove="Models\Mappings\CondominiumFee.hbm.xml" />
    <None Remove="Models\Mappings\CondominiumInstallment.hbm.xml" />
    <None Remove="Models\Mappings\CondominiumInstallmentStatus.hbm.xml" />
    <None Remove="Models\Mappings\Document.hbm.xml" />
    <None Remove="Models\Mappings\DocumentAccess.hbm.xml" />
    <None Remove="Models\Mappings\Expense.hbm.xml" />
    <None Remove="Models\Mappings\ExpenseAllocation.hbm.xml" />
    <None Remove="Models\Mappings\ExpensePaymentStatus.hbm.xml" />
    <None Remove="Models\Mappings\ExpenseType.hbm.xml" />
    <None Remove="Models\Mappings\FiscalYear.hbm.xml" />
    <None Remove="Models\Mappings\FiscalYearStatus.hbm.xml" />
    <None Remove="Models\Mappings\MenuItem.hbm.xml" />
    <None Remove="Models\Mappings\Message.hbm.xml" />
    <None Remove="Models\Mappings\MillesimalTable.hbm.xml" />
    <None Remove="Models\Mappings\Payment.hbm.xml" />
    <None Remove="Models\Mappings\RealEstateUnit.hbm.xml" />
    <None Remove="Models\Mappings\Receipt.hbm.xml" />
    <None Remove="Models\Mappings\Supplier.hbm.xml" />
    <None Remove="Models\Mappings\ExtraordinaryWork.hbm.xml" />
    <None Remove="Models\Mappings\Maintenance.hbm.xml" />
    <None Remove="Models\Mappings\WorkQuote.hbm.xml" />
    <None Remove="Models\Mappings\WorkQuoteDocument.hbm.xml" />
    <None Remove="Models\Mappings\SupplierContract.hbm.xml" />
    <None Remove="Models\Mappings\Tenant.hbm.xml" />
    <None Remove="Models\Mappings\UnitMillesimal.hbm.xml" />
    <None Remove="Models\Mappings\UnitOwner.hbm.xml" />
    <None Remove="Models\Mappings\UnitTenant.hbm.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Models\Mappings\Budget.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\BudgetItem.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\BudgetStatus.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ChartOfAccounts.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ChartOfAccountsCategory.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ChartOfAccountsCategoryTemplate.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ChartOfAccountsTemplate.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ChartOfAccountsTemplateItem.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Communication.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CommunicationRead.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Condominium.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CondominiumAddress.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CondominiumCadastralData.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CondominiumFee.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CondominiumInstallment.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\CondominiumInstallmentStatus.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Document.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\DocumentAccess.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Expense.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ExpenseAllocation.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ExpensePaymentStatus.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ExpenseType.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\FiscalYear.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\FiscalYearStatus.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\MenuItem.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Message.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\MillesimalTable.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Payment.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\RealEstateUnit.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Receipt.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Supplier.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\ExtraordinaryWork.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Maintenance.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\WorkQuote.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\WorkQuoteDocument.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\SupplierContract.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\Tenant.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\UnitMillesimal.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\UnitOwner.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\UserTenant.hbm.xml" />
    <EmbeddedResource Include="Models\Mappings\UnitTenant.hbm.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.3" />
    <PackageReference Include="CPQ.Core" Version="1.3.7" />
    <PackageReference Include="CPQ.Core.EventSource" Version="1.0.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Hangfire.Core" Version="1.8.18" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dto\Comunicazioni\" />
    <Folder Include="Dto\Condominio\" />
    <Folder Include="Dto\Documenti\" />
    <Folder Include="Dto\Fornitori\" />
    <Folder Include="Dto\Millesimi\" />
    <Folder Include="Dto\Rate\" />
    <Folder Include="Dto\Spese\" />
    <Folder Include="Dto\Unita\" />
    <Folder Include="Orchestators\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
