using System.Collections.Generic;

namespace DomuWave.Services.Models
{
    public class BillingGroup : TenantEntity<int>
    {
        public virtual Condominium Condominium    { get; set; } = null!;
        public virtual string?     ContactEmail   { get; set; }
        public virtual string?     ContactPhone   { get; set; }
        public virtual bool        IsAutoGenerated { get; set; }

        public virtual IList<RealEstateUnit> Units { get; set; } = new List<RealEstateUnit>();

        public override int GetHashCode() => Id.GetHashCode();
    }
}
