using CPQ.Core.Extensions;
using DomuWave.Services.Dto.BillingGroup;
using DomuWave.Services.Models;

namespace DomuWave.Services.Interfaces.Extensions;

public static class BillingGroupMappingExtensions
{
    public static BillingGroupReadDto ToReadDto(this BillingGroup entity)
    {
        if (entity == null) return null;
        var dto = new BillingGroupReadDto
        {
            CondominiumId   = entity.Condominium?.Id   ?? 0,
            CondominiumName = entity.Condominium?.Name ?? string.Empty,
            Name            = entity.Name,
            ContactEmail    = entity.ContactEmail ?? string.Empty,
            ContactPhone    = entity.ContactPhone ?? string.Empty,
            Notes           = entity.Description  ?? string.Empty,
            IsAutoGenerated = entity.IsAutoGenerated,
            Units           = entity.Units
                .Where(u => !u.IsDeleted)
                .Select(u => u.ToBillingGroupUnitDto())
                .ToList(),
        };
        dto.SetTraceInfo(entity);
        return dto;
    }

    public static BillingGroupUnitDto ToBillingGroupUnitDto(this RealEstateUnit unit) => new()
    {
        UnitId         = unit.Id,
        InternalNumber = unit.InternalNumber ?? string.Empty,
        DisplayName    = unit.DisplayName    ?? string.Empty,
        UnitType       = unit.UnitType       ?? string.Empty,
    };

    public static BillingGroup ToEntity(this CreateBillingGroupDto dto, Condominium condominium, Tenant tenant) =>
        new()
        {
            Condominium     = condominium,
            Tenant          = tenant,
            Name            = dto.Name,
            ContactEmail    = dto.ContactEmail,
            ContactPhone    = dto.ContactPhone,
            Description     = dto.Notes,
            IsAutoGenerated = false,
        };

    public static void ApplyUpdate(this BillingGroup entity, UpdateBillingGroupDto dto)
    {
        
        if (dto != null)
        {
            entity.Name = string.IsNullOrEmpty(dto.Name) ? string.Empty : dto.Name;
            entity.ContactEmail = dto.ContactEmail;
            entity.ContactPhone = dto.ContactPhone;
            entity.Description = string.IsNullOrEmpty(dto.Notes) ? string.Empty : dto.Notes;
        }
    }
}
