<template>
  <div>
    <ToolbarRow>
      <template #left>
        <button v-if="canEdit" class="btn btn-ghost btn-sm" @click="runSuggest" :disabled="suggesting">
          <span v-if="suggesting" class="spinner" style="width:12px;height:12px"></span>
          <span v-else>✦ Suggerisci automaticamente</span>
        </button>
      </template>
      <template #right>
        <button v-if="canEdit" class="btn btn-primary" @click="openGroupModal()">
          <i class="pi pi-plus" style="font-size:0.8rem;margin-right:0.35rem"></i>Nuovo gruppo
        </button>
      </template>
    </ToolbarRow>

    <div class="card">
      <div v-if="loadingGroups" class="loading-state"><div class="spinner"></div></div>

      <div v-else-if="!billingGroups.length" class="empty-state" style="padding:2rem">
        <div class="empty-icon" style="font-size:1.4rem">◈</div>
        <div>Nessun gruppo configurato — le quote vengono generate individualmente per unità</div>
      </div>

      <div v-else class="table-wrap">
        <table class="cards-on-mobile">
          <thead>
            <tr>
              <th>Nome gruppo</th>
              <th>Email contatto</th>
              <th>Unità incluse</th>
              <th>Tipo</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="g in billingGroups" :key="g.id">
              <td data-label="Nome gruppo">{{ g.name }}</td>
              <td data-label="Email contatto" class="text-secondary">{{ g.contactEmail || '—' }}</td>
              <td data-label="Unità incluse">
                <span v-for="u in g.units" :key="u.unitId" class="unit-chip">
                  {{ u.internalNumber }}<span v-if="u.displayName" class="text-muted"> – {{ u.displayName }}</span>
                </span>
              </td>
              <td data-label="Tipo">
                <span class="badge" :class="g.isAutoGenerated ? 'badge-muted' : 'badge-green'">
                  {{ g.isAutoGenerated ? 'Auto' : 'Manuale' }}
                </span>
              </td>
              <td>
                <div class="row-actions">
                  <button v-if="canEdit" class="btn-icon" @click="openBalanceModal(g)" title="Saldo iniziale gruppo">₿</button>
                  <button v-if="canEdit" class="btn-icon" @click="openGroupModal(g)" title="Modifica">✎</button>
                  <button v-if="canEdit" class="btn-icon" @click="deleteGroup(g.id)" style="color:var(--accent-red)" title="Elimina">✕</button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal Suggerimenti -->
    <div class="modal-overlay" v-if="showSuggestModal" @mousedown.self="showSuggestModal=false">
      <div class="modal modal--wide">
        <div class="modal-header">
          <h2>Suggerimenti gruppi di fatturazione</h2>
          <button class="btn-icon" @click="showSuggestModal=false">✕</button>
        </div>
        <div class="modal-body">
          <div v-if="suggestionResult.suggestions.length">
            <p class="suggest-intro">I seguenti gruppi possono essere creati automaticamente:</p>
            <table class="inner-table" style="margin-bottom:1rem">
              <thead>
                <tr>
                  <th><input type="checkbox" @change="toggleAllSuggestions" :checked="selectedSuggestions.length === suggestionResult.suggestions.length" /></th>
                  <th>Nome suggerito</th>
                  <th>Email</th>
                  <th>Unità</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(s, i) in suggestionResult.suggestions" :key="i">
                  <td><input type="checkbox" v-model="selectedSuggestions" :value="s" /></td>
                  <td><input class="form-input" style="min-width:180px" v-model="s.suggestedName" /></td>
                  <td><input class="form-input" style="min-width:150px" v-model="s.contactEmail" /></td>
                  <td>
                    <span v-for="u in s.units" :key="u.unitId" class="unit-chip">{{ u.internalNumber }}</span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div v-else>
            <p class="text-secondary" style="font-size:0.875rem">Nessun gruppo univoco trovato. Tutti i proprietari hanno unità con set diversi di comproprietari.</p>
          </div>
          <div v-if="suggestionResult.ambiguousUnits.length" class="ambiguous-box">
            <p class="ambiguous-title">Unità con proprietari ambigui (da configurare manualmente):</p>
            <div class="ambiguous-units">
              <span v-for="u in suggestionResult.ambiguousUnits" :key="u.unitId" class="unit-chip unit-chip--warn">
                {{ u.internalNumber }}<span v-if="u.displayName"> – {{ u.displayName }}</span>
              </span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-ghost" @click="showSuggestModal=false">Chiudi</button>
          <button v-if="suggestionResult.suggestions.length" class="btn btn-primary" @click="applySelected" :disabled="!selectedSuggestions.length || applyingGroups">
            <span v-if="applyingGroups" class="spinner" style="width:14px;height:14px"></span>
            Crea {{ selectedSuggestions.length }} gruppo{{ selectedSuggestions.length !== 1 ? 'i' : '' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Modal Create/Edit gruppo -->
    <div class="modal-overlay" v-if="showGroupModal" @mousedown.self="showGroupModal=false">
      <div class="modal">
        <div class="modal-header">
          <h2>{{ editingGroup ? 'Modifica gruppo' : 'Nuovo gruppo' }}</h2>
          <button class="btn-icon" @click="showGroupModal=false">✕</button>
        </div>
        <div class="modal-body">
          <div class="form-group" :class="{ 'has-error': groupErrors.name }">
            <label class="form-label">Nome gruppo *</label>
            <input class="form-input" v-model="groupForm.name" @input="delete groupErrors.name" placeholder="Es. Ferrari Mario" />
            <span v-if="groupErrors.name" class="field-error">{{ groupErrors.name }}</span>
          </div>
          <div class="form-grid">
            <div class="form-group">
              <label class="form-label">Email contatto</label>
              <input class="form-input" type="email" v-model="groupForm.contactEmail" />
            </div>
            <div class="form-group">
              <label class="form-label">Telefono</label>
              <input class="form-input" v-model="groupForm.contactPhone" />
            </div>
          </div>
          <div class="form-group" style="margin-top:0.75rem">
            <label class="form-label">Unità incluse nel gruppo</label>
            <div class="unit-checklist">
              <label v-for="u in condoUnits" :key="u.id" class="unit-check-item">
                <input type="checkbox" :value="u.id" v-model="groupForm.unitIds" />
                <span class="unit-number">{{ u.internalNumber }}</span>
                <span v-if="u.displayName" class="text-secondary" style="font-size:0.8rem"> – {{ u.displayName }}</span>
                <span class="text-muted" style="font-size:0.75rem"> ({{ u.unitType }})</span>
              </label>
            </div>
            <p v-if="!condoUnits.length" class="text-muted" style="font-size:0.8rem">Nessuna unità disponibile</p>
          </div>
          <div class="form-group" style="margin-top:0.5rem">
            <label class="form-label">Note</label>
            <textarea class="form-textarea" v-model="groupForm.notes" rows="2"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-ghost" @click="showGroupModal=false">Annulla</button>
          <button class="btn btn-primary" @click="saveGroup" :disabled="savingGroup">
            <span v-if="savingGroup" class="spinner" style="width:14px;height:14px"></span>
            {{ editingGroup ? 'Salva' : 'Crea' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Modal Saldo iniziale gruppo -->
    <div class="modal-overlay" v-if="showBalanceModal" @mousedown.self="showBalanceModal=false">
      <div class="modal">
        <div class="modal-header">
          <h2>Saldo iniziale — {{ balanceGroup?.name }}</h2>
          <button class="btn-icon" @click="showBalanceModal=false">✕</button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label">Criterio di ripartizione</label>
            <select class="form-select" v-model="balanceForm.criterion">
              <option value="millesimal">Per millesimi (tabella principale)</option>
              <option value="equal">In parti uguali</option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-label">Esercizio fiscale *</label>
            <select class="form-select" v-model.number="balanceForm.fiscalYearId" @change="loadGroupBalanceState">
              <option :value="null">— Seleziona —</option>
              <option v-for="fy in fiscalYears" :key="fy.id" :value="fy.id">{{ fy.code }}</option>
            </select>
          </div>
          <div v-if="balanceForm.fiscalYearId">
            <div v-if="balanceLoading" class="loading-state"><div class="spinner"></div></div>
            <div v-else-if="!balanceEditable" class="empty-state" style="padding:1rem">
              {{ balanceNotEditableReason }}
            </div>
            <template v-else>
              <div class="form-group" style="margin-top:0.5rem">
                <label class="form-label">Importo totale da ripartire (€) *</label>
                <input class="form-input" type="number" step="0.01" v-model.number="balanceForm.totalAmount" />
              </div>
              <div class="form-group">
                <label class="form-label">Note</label>
                <textarea class="form-textarea" v-model="balanceForm.notes" rows="2"></textarea>
              </div>
            </template>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-ghost" @click="showBalanceModal=false">Annulla</button>
          <button
            v-if="balanceEditable"
            class="btn btn-primary"
            @click="saveGroupBalance"
            :disabled="balanceSaving || !balanceForm.fiscalYearId"
          >
            <span v-if="balanceSaving" class="spinner" style="width:14px;height:14px"></span>
            Ripartisci e salva
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { billingGroupApi, unitApi, fiscalYearApi } from '@/services/api'
import { usePermissions } from '@/composables/usePermissions'
import { useAppStore } from '@/stores/app'
import ToolbarRow from '@/components/ToolbarRow.vue'

const { canEdit } = usePermissions()
const store = useAppStore()
const route = useRoute()

const condominiumId = computed(() => Number(route.params.id) || store.selectedCondominioId)

const billingGroups    = ref([])
const condoUnits       = ref([])
const loadingGroups    = ref(false)
const suggesting       = ref(false)
const applyingGroups   = ref(false)
const savingGroup      = ref(false)
const showGroupModal   = ref(false)
const showSuggestModal = ref(false)
const editingGroup     = ref(null)
const groupErrors      = ref({})
const suggestionResult = ref({ suggestions: [], ambiguousUnits: [] })
const selectedSuggestions = ref([])

const defaultGroupForm = () => ({ name: '', contactEmail: '', contactPhone: '', notes: '', unitIds: [] })
const groupForm = ref(defaultGroupForm())

const showBalanceModal      = ref(false)
const balanceGroup          = ref(null)
const balanceSaving         = ref(false)
const balanceLoading        = ref(false)
const balanceEditable       = ref(false)
const balanceNotEditableReason = ref('')
const fiscalYears           = ref([])
const defaultBalanceForm = () => ({ fiscalYearId: null, totalAmount: 0, notes: '', criterion: 'millesimal' })
const balanceForm = ref(defaultBalanceForm())

async function loadBillingGroups() {
  if (!condominiumId.value) return
  loadingGroups.value = true
  try {
    const { data } = await billingGroupApi.getByCondominium(condominiumId.value)
    billingGroups.value = data ?? []
  } catch {
    // global error handler
  } finally {
    loadingGroups.value = false
  }
}

async function loadCondoUnits() {
  if (!condominiumId.value) return
  try {
    const { data } = await unitApi.getByCondominium(condominiumId.value)
    condoUnits.value = (data ?? []).filter(u => u.isActive)
  } catch { /* ignore */ }
}

function openGroupModal(group = null) {
  editingGroup.value  = group?.id ?? null
  groupErrors.value   = {}
  groupForm.value     = group
    ? { name: group.name, contactEmail: group.contactEmail || '', contactPhone: group.contactPhone || '', notes: group.notes || '', unitIds: group.units.map(u => u.unitId) }
    : defaultGroupForm()
  showGroupModal.value = true
}

async function saveGroup() {
  if (!groupForm.value.name?.trim()) {
    groupErrors.value = { name: 'Il nome è obbligatorio' }
    return
  }
  savingGroup.value = true
  try {
    if (editingGroup.value) {
      await billingGroupApi.update(editingGroup.value, groupForm.value)
      store.toast('Gruppo aggiornato', 'success')
    } else {
      await billingGroupApi.create({ ...groupForm.value, condominiumId: condominiumId.value })
      store.toast('Gruppo creato', 'success')
    }
    showGroupModal.value = false
    await loadBillingGroups()
  } catch (err) {
    if (!err?.response) store.toast('Impossibile raggiungere il server', 'error')
  } finally {
    savingGroup.value = false
  }
}

async function deleteGroup(id) {
  if (!confirm('Eliminare questo gruppo? Le unità associate non verranno eliminate.')) return
  try {
    await billingGroupApi.delete(id)
    store.toast('Gruppo eliminato', 'success')
    await loadBillingGroups()
  } catch (err) {
    if (!err?.response) store.toast('Impossibile raggiungere il server', 'error')
  }
}

async function openBalanceModal(group) {
  if (!group.units?.length) {
    store.toast('Il gruppo non contiene unità', 'error')
    return
  }
  balanceGroup.value  = group
  balanceForm.value   = defaultBalanceForm()
  balanceEditable.value = false
  showBalanceModal.value = true

  try {
    const { data } = await fiscalYearApi.getByCondominium(condominiumId.value)
    fiscalYears.value = (data ?? []).filter(f => !f.isDeleted)
    const active = fiscalYears.value.find(f => f.isActive) ?? fiscalYears.value[0]
    if (active) {
      balanceForm.value.fiscalYearId = active.id
      await loadGroupBalanceState()
    }
  } catch { /* handled by interceptor */ }
}

async function loadGroupBalanceState() {
  if (!balanceForm.value.fiscalYearId || !balanceGroup.value) return
  balanceLoading.value = true
  try {
    const firstUnitId = balanceGroup.value.units[0].unitId
    const { data } = await unitApi.getOpeningBalance(firstUnitId, balanceForm.value.fiscalYearId)
    balanceEditable.value = !!data.isEditable
    balanceNotEditableReason.value = data.isClosed
      ? "L'esercizio selezionato è chiuso: il saldo non è più modificabile."
      : 'Il saldo di apertura non è modificabile: non è il primo esercizio del condominio.'
  } catch {
    balanceEditable.value = false
  } finally {
    balanceLoading.value = false
  }
}

async function saveGroupBalance() {
  if (!balanceGroup.value || !balanceForm.value.fiscalYearId) return
  balanceSaving.value = true
  try {
    await billingGroupApi.setOpeningBalance(balanceGroup.value.id, {
      fiscalYearId: balanceForm.value.fiscalYearId,
      totalAmount:  balanceForm.value.totalAmount,
      notes:        balanceForm.value.notes,
      criterion:    balanceForm.value.criterion,
    })
    store.toast('Saldo iniziale ripartito tra le unità del gruppo', 'success')
    showBalanceModal.value = false
  } catch (err) {
    if (!err?.response) store.toast('Impossibile raggiungere il server', 'error')
  } finally {
    balanceSaving.value = false
  }
}

async function runSuggest() {
  suggesting.value = true
  try {
    const { data } = await billingGroupApi.suggest(condominiumId.value)
    suggestionResult.value    = { suggestions: data.suggestions ?? [], ambiguousUnits: data.ambiguousUnits ?? [] }
    selectedSuggestions.value = [...suggestionResult.value.suggestions]
    showSuggestModal.value    = true
  } catch (err) {
    if (!err?.response) store.toast('Impossibile raggiungere il server', 'error')
  } finally {
    suggesting.value = false
  }
}

function toggleAllSuggestions(e) {
  selectedSuggestions.value = e.target.checked ? [...suggestionResult.value.suggestions] : []
}

async function applySelected() {
  if (!selectedSuggestions.value.length) return
  applyingGroups.value = true
  try {
    await billingGroupApi.applySuggestions(condominiumId.value, selectedSuggestions.value)
    store.toast(`${selectedSuggestions.value.length} gruppo/i creati`, 'success')
    showSuggestModal.value = false
    await loadBillingGroups()
  } catch (err) {
    if (!err?.response) store.toast('Impossibile raggiungere il server', 'error')
  } finally {
    applyingGroups.value = false
  }
}

function loadAll() { Promise.all([loadBillingGroups(), loadCondoUnits()]) }

onMounted(loadAll)
onUnmounted(() => window.removeEventListener('app:refresh', loadAll))
window.addEventListener('app:refresh', loadAll)
watch(condominiumId, loadAll)
</script>

<style scoped>
.unit-chip {
  display: inline-block;
  background: var(--accent-glow, #eef2ff);
  border: 1px solid var(--border);
  border-radius: 4px;
  font-size: 0.775rem;
  padding: 0.1rem 0.4rem;
  margin: 0.1rem 0.2rem 0.1rem 0;
  white-space: nowrap;
}
.unit-chip--warn {
  background: #fff7ed;
  border-color: #f97316;
  color: #c2410c;
}

.unit-checklist {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  max-height: 200px;
  overflow-y: auto;
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.5rem 0.75rem;
  margin-top: 0.25rem;
}
.unit-check-item {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.875rem;
  cursor: pointer;
}
.unit-check-item input[type="checkbox"] { cursor: pointer; }

.suggest-intro { font-size: 0.875rem; color: var(--text-secondary); margin-bottom: 0.75rem; }

.ambiguous-box {
  margin-top: 1rem;
  border: 1px solid #f97316;
  border-radius: 6px;
  padding: 0.75rem 1rem;
  background: #fff7ed;
}
.ambiguous-title { font-size: 0.8rem; font-weight: 600; color: #c2410c; margin-bottom: 0.5rem; }
.ambiguous-units { display: flex; flex-wrap: wrap; gap: 0.35rem; }

.has-error .form-input { border-color: var(--accent-red, #e53e3e); }
.field-error { font-size: 0.78rem; color: var(--accent-red, #e53e3e); margin-top: 0.2rem; }
.modal--wide { width: min(760px, 96vw); max-width: min(760px, 96vw); }
</style>
