-- Migration: aggiungi tabella BillingGroup e FK su RealEstateUnit
-- Data: 2026-04-18

-- 1. Tabella BillingGroup
CREATE TABLE BillingGroup (
    Id                   INT            NOT NULL PRIMARY KEY,
    TenantId             UNIQUEIDENTIFIER NOT NULL,
    CondominiumId        INT            NOT NULL,
    Name                 NVARCHAR(200)  NOT NULL,
    ContactEmail         NVARCHAR(255)  NULL,
    ContactPhone         NVARCHAR(30)   NULL,
    Notes                NVARCHAR(1000) NULL,
    IsAutoGenerated      BIT            NOT NULL DEFAULT 0,
    CreatedById          INT            NOT NULL,
    CreatedByFullName    NVARCHAR(200)  NULL,
    LastUpdatedById      INT            NULL,
    LastUpdatedByFullName NVARCHAR(200) NULL,
    IsDeleted            BIT            NOT NULL DEFAULT 0,
    CreationDate         DATETIME2      NOT NULL,
    LastUpdateDate       DATETIME2      NULL,

    CONSTRAINT FK_BillingGroup_Condominium FOREIGN KEY (CondominiumId) REFERENCES Condominium(Id)
);

-- 2. FK su RealEstateUnit
ALTER TABLE RealEstateUnit ADD BillingGroupId INT NULL;
ALTER TABLE RealEstateUnit ADD CONSTRAINT FK_RealEstateUnit_BillingGroup
    FOREIGN KEY (BillingGroupId) REFERENCES BillingGroup(Id);

-- 3. Hilo entry
INSERT INTO hibernate_unique_key (entity_type, next_hi)
SELECT 'BillingGroup', 1
WHERE NOT EXISTS (
    SELECT 1 FROM hibernate_unique_key WHERE entity_type = 'BillingGroup'
);
